config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    resources :snakes, only: %i[new create show edit update]

    root to: 'snakes#index'
  end

  constraints Clearance::Constraints::SignedOut.new do
    scope :battle, defaults: { format: 'json' } do
      get 'snakes/:id', to: 'api/snakes#show'
      post 'snakes/:id/start', to: 'api/games#create'
      post 'snakes/:id/move', to: 'api/moves#create'
      post 'snakes/:id/end', to: 'api/games#destroy'
    end

    root to: 'clearance/sessions#new', as: :signed_out_root
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/game_participant.rb
class GameParticipant < ApplicationRecord
  belongs_to :game
  belongs_to :snake
end

app/models/snake.rb
class Snake < ApplicationRecord
  scope :alphabetical_order, -> { order(name: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  include Clearance::User
end

app/controllers/api/games_controller.rb
class Api::GamesController < ActionController::API
  def create
    @game = Game.find_or_initialize_by(external_id: params[:game][:id])
    @game.timeout = params[:game][:timeout]
    @game.width = params[:board][:width]
    @game.height = params[:board][:height]
    @game.snake_count = params[:board][:snakes].length
    @game.mode = params.dig(:game, :ruleset, :name) || 'standard'
    @game.save!

    @participant = GameParticipant.find_or_initialize_by(game_id: @game.id, snake_id: params[:id])
    @participant.save!
  end

  def destroy
    @game = Game.find_by(external_id: params[:game][:id])
    @game.ended_at = Time.current
    @game.save!
  end
end

app/controllers/api/moves_controller.rb
class Api::MovesController < ActionController::API
  def create
    render json: { move: 'up', shout: 'Going up!' }
  end
end

app/controllers/api/snakes_controller.rb
class Api::SnakesController < ActionController::API
  def show
    @snake = Snake.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/secure_controller.rb
class SecureController < ApplicationController
	before_action :require_login
	
end

app/controllers/snakes_controller.rb
class SnakesController < SecureController
  def index
    @snakes = Snake.alphabetical_order
  end

  def new
    @snake = Snake.new
  end

  def create
    @snake = Snake.new(snake_params)

    if @snake.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @snakes = Snake.alphabetical_order
    @snake = Snake.find params[:id]
  end

  def edit
    @snake = Snake.find(params[:id])
  end

  def update
    @snake = Snake.find(params[:id])
    @snake.assign_attributes(snake_params)

    if @snake.save
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def snake_params
    params.require(:snake).permit(
      :name, :color, :head, :tail
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaximumBs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>
    
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/snakes/_form.html.erb
<%= form_with model: snake do |form| %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div>
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>
  
  <div>
    <%= form.label :head %>
    <%= form.text_field :head %>
  </div>
  
  <div>
    <%= form.label :tail %>
    <%= form.text_field :tail %>
  </div>

  <div><%= form.submit %></div>

<% end %>

app/views/snakes/_sidebar.html.erb
<h1>Snakes</h1>

<div id="snakes">
  <% @snakes.each do |snake| %>
    <div>
      <%= link_to snake.name, snake %>
      <%= link_to 'E', edit_snake_path(snake) %>
    </div>
  <% end %>

  <%= link_to 'Create Snake', new_snake_path %>
</div>

app/views/snakes/edit.html.erb
<h1>Edit <%= @snake.name %></h1>

<%= render 'form', snake: @snake %>

app/views/snakes/index.html.erb
<h1>Maximum BS</h1>

<div>
	<div><%= render 'sidebar' %></div>

	<div>
		<h2>Pick a snake, any snake</h2>
	</div>
</div>

app/views/snakes/new.html.erb
<h1>Create Snake</h1>

<%= render 'form', snake: @snake %>

app/views/snakes/show.html.erb
<h1>Maximum BS</h1>

<div>
  <div><%= render 'sidebar' %></div>

  <div>
    <h1>Results for <%= @snake.name %></h1>

    <div id="game-results">
      <%# @snake.games.reverse_chronological.each do |game| %>
        <%# game.started_at %>
        <%# game.ended_at %>
        <%# game.result %>
      <%#x end %>
    </div>
  </div>
</div>